checks:
    javascript: true
build:
    dependencies:
        before:
            - npm install istanbul   # or add it as part of your package.json
    tests:
        override:
            -
                command: './node_modules/.bin/istanbul cover --report clover ./node_modules/.bin/_mocha test/**/*'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
